server:
  port: 8080

spring:
  application:
    name: ecommerce-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3310/ecommerce_db}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:root}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    clean-on-validation-error: true

security:
  jwt:
    secret: ${SECURITY_JWT_SECRET:change-this-secret-to-a-long-random-production-value-32-bytes}
    access-token-minutes: ${SECURITY_JWT_ACCESS_TOKEN_MINUTES:15}
    refresh-token-days: ${SECURITY_JWT_REFRESH_TOKEN_DAYS:7}

bakong:
  # Base URL points to the SIT Sandbox instead of Production
  api-url: ${BAKONG_API_URL:https://nbc.gov.kh}

  # Paste your SIT Sandbox bearer token inside this fallback variable
  token: ${BAKONG_AUTH_TOKEN:bkv2_03c348cb41e49237554c9deddc1940e6c0da68f4c610e4b4ac4a9f73a6}

  account-id: ${BAKONG_ACCOUNT_ID:sunlang_orn@bkrt}
  merchant-name: ${BAKONG_MERCHANT_NAME:Liang Store}
  merchant-city: ${BAKONG_MERCHANT_CITY:Phnom Penh}