
ALTER TABLE categories ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

UPDATE categories
SET status = CASE
    WHEN is_active = TRUE THEN 'ACTIVE'
    ELSE 'INACTIVE'
END;

ALTER TABLE categories DROP COLUMN is_active;

ALTER TABLE products ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE';

UPDATE products
SET status = CASE
    WHEN is_active = TRUE THEN 'ACTIVE'
    ELSE 'INACTIVE'
END;

ALTER TABLE products DROP COLUMN is_active;

ALTER TABLE products ADD COLUMN version BIGINT NOT NULL DEFAULT 0;

ALTER TABLE addresses ADD COLUMN address_type VARCHAR(20) NOT NULL DEFAULT 'SECONDARY';

UPDATE addresses
SET address_type = CASE
    WHEN is_default = TRUE THEN 'DEFAULT'
    ELSE 'SECONDARY'
END;

ALTER TABLE addresses DROP COLUMN is_default;